### PR TITLE
Added Meetup Starter Kit

### PR DESCRIPTION
**Pull request by bnb**
Added MSK, a la https://github.com/nodejs/evangelism/issues/162.
Included as much feedback as I could.

After this is reviewed and merged, I will send to nodejs/new.nodejs.org
as a page under the contribute template. If I don't do it in a timely
manner, feel free to do it yourself.

### CODE REVIEW

**Comment by mikeal** [comment]
Should we just commit this to the website with a link from the main Get Involved page?

**Comment by bnb** [comment]
I posted it here for feedback from the Evangelism WG, if there was any. If nobody has feedback, I can submit it to the new.nodejs.org repo.

**Comment by mikeal** [comment]
@bnb cool.

**Comment by bnb** [comment]
@mikeal No idea how this PR got sent to my personal repo. My bad.

**Pull request closed without merging**
